{{- $demoUser := .Values.jupyterHub.demoUser -}}
{{- range .Values.jupyterHub.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-{{ $demoUser }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: jupyterhub
data: 
{{- if eq .name "jupyterhub-singleuser-profile" }}
{{- range $.Values.jupyterHub.image }}
  profile: |
    gpu: '0'
    last_selected_image: {{ .name }}:{{ .tag }}
    last_selected_size: {{ .imageSize }}
{{- end }}
{{- else }}
  JUPYTER_PRELOAD_REPOS: {{ $.Values.gitURL }}
{{- end }}
{{- end }}