apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-detect
  labels:
    app: boat-detect
    app.kubernetes.io/component: boat-detect
    app.kubernetes.io/instance: boat-detect
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: boat-demo
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi8
  name: boat-detect
  namespace: boats-demo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: boat-detect:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /detect
    git:
      uri: https://github.com/redhat-naps-da/boat-detect
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-ubi8-py38-opengl:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: boat-detect-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: boat-detect-github-webhook-secret
    type: GitHub
  - imageChange: null
    type: ImageChange
  - type: ConfigChange