- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-detect
    labels:
      app: boat-group
      app.kubernetes.io/component: boat-group
      app.kubernetes.io/instance: boat-group
      app.kubernetes.io/name: python
      app.kubernetes.io/part-of: boat-demo
      app.openshift.io/runtime: python
      app.openshift.io/runtime-version: 3.8-ubi8
    name: boat-group
    namespace: boats-demo
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: boat-group:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /group
      git:
        uri: https://github.com/redhat-naps-da/boat-detect
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.8-ubi8
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - generic:
        secretReference:
          name: boat-group-generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: boat-group-github-webhook-secret
      type: GitHub
    - imageChange: null
      type: ImageChange
    - type: ConfigChange