- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-group
    labels:
      app: boat-group
      app.kubernetes.io/component: boat-group
      app.kubernetes.io/instance: boat-group
      app.kubernetes.io/name: python
      app.kubernetes.io/part-of: boat-demo
      app.openshift.io/runtime: python
      app.openshift.io/runtime-version: 3.8-ubi8
    name: boat-group
    namespace: boats-demo
  spec:
    clusterIP: null
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: boat-group
      deploymentconfig: boat-group
    sessionAffinity: None
    type: ClusterIP