apiVersion: v1
data:
  JUPYTER_PRELOAD_REPOS: https://github.com/redhat-naps-da/boat-demo.git
kind: ConfigMap
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-singleuser-profile-USERNAME-envs
  namespace: boats-demo