apiVersion: v1
data:
  profile: |
    gpu: '0'
    last_selected_image: boat-demo-notebook-image:latest
    last_selected_size: Large
kind: ConfigMap
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-singleuser-profile-USERNAME
  namespace: boats-demo