apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-demo
  labels:
    app: s2i-ubi8-py38-opengl
    app.kubernetes.io/component: s2i-ubi8-py38-opengl
    app.kubernetes.io/instance: s2i-ubi8-py38-opengl
  name: {{ .Values.s2iopengl.image.name }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: {{ .Values.s2iopengl.image.lookupPolicy.local }}