{{- range .Values.apps }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: {{ $.Values.gitURL }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/part-of: {{ $.Values.pattern.name }}
{{- if or (eq .name "boat-detect") (eq .name "boat-identify") (eq .name "boat-group") }}
    app.openshift.io/runtime: {{ .runtime }}
    app.openshift.io/runtimeVersion: {{ .runtimeVersion }}
{{- end }}
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .name }}:{{ .imageTag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: {{ .contextDir }}
    git:
      uri: {{ $.Values.gitURL }}
    type: Git
  strategy:
{{- if eq .name "boat-demo-notebook-image" }}
{{ include "boat-demo.dockerDefault" . | indent 4 }}
{{- else if eq .name "s2i-ubi8-py38-opengl" }}
{{ include "boat-demo.dockerIS" . | indent 4 }}
{{- else }}
    sourceStrategy:
      from:
        kind: ImageStreamTag
{{- if or (eq .name "boat-identify") (eq .name "boat-group") }}
        name: python:3.8-ubi8
        namespace: openshift
{{- else }}
        name: s2i-ubi8-py38-opengl:latest
{{- end }}
    type: Source
{{- end }}
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: {{ .name }}-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: {{ .name }}-github-webhook-secret
    type: GitHub
  - type: ConfigChange
{{- end }}
