apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-detect
  labels:
    app: boat-detect
    app.kubernetes.io/component: boat-detect
    app.kubernetes.io/instance: boat-detect
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: boat-demo
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi8
  name: boat-detect
  namespace: boats-demo
spec:
  lookupPolicy:
    local: false