namespace: boats-demo

odh:
  kfdef:
    name: opendatahub
  applications:
    - name: odh-common
      repoRef:
        name: manifests
        path: odh-common
    - name: jupyterhub
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
      params:
        name: s3_endpoint_url
        value: s3.odh.com
    - name: notebook-images
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
  repos:
    - name: kf-manifests
      uri: 'https://github.com/kubeflow/manifests/tarball/v1.2-branch'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.9'

notebook:
  image:
    name: boat-demo-notebook-image
    lookupPolicy:
      local: false
    tags:
      kind: ImageStreamTag
      name: boat-demo-notebook-image:latest
  build:
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
    nodeSelector: null
    runPolicy: Serial
    source:
      contextDir: /notebook
      git:
        uri: https://github.com/redhat-naps-da/boat-demo.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers:
      generic:
        secretReference:
          name: boat-demo-notebook-image-generic-webhook-secret
        type: Generic
      github:
        secretReference:
          name: boat-demo-notebook-image-github-webhook-secret
        type: GitHub

s2iopengl:
  image:
    name: s2i-ubi8-py38-opengl
    lookupPolicy:
      local: false
    tags:
      kind: ImageStreamTag
      name: s2i-ubi8-py38-opengl:latest
  build:
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
    nodeSelector: null
    runPolicy: Serial
    source:
      contextDir: /s2i-ubi8-py38-opengl
      git:
        uri: https://github.com/redhat-naps-da/boat-demo
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.8-ubi8
          namespace: openshift
        dockerfilePath: Dockerfile
      type: Docker
    triggers:
      generic:
        secretReference:
          name: s2i-ubi8-py38-opengl-generic-webhook-secret
        type: Generic
      github:
        secretReference:
          name: s2i-ubi8-py38-opengl-github-webhook-secret
        type: GitHub
